version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allowance-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - allowance-network

  nginx:
    image: nginx:alpine
    container_name: allowance-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - allowance-network

  node:
    image: node:18-alpine
    container_name: allowance-node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - allowance-network
    command: sh -c "npm install && npm run dev"

networks:
  allowance-network:
    driver: bridge
